name: Release to npm

on:
  release:
    types: [created]

jobs:
  publish:
    name: "Release"
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ tests, try-scenarios ]

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
